# Generated by Django 3.1.5 on 2021-02-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_image'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='post.Post'),
        ),
    ]
